### ISSUE TITLE
responsive_images plugin make the build crashing during preprocessing.

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#73]
Hello,
Generation fails at the Preprocessing task, just after i've upgraded my project and enabled the   responsive_images plugin. 
My environment:
Windows 10, Python 2.7.13 :: Anaconda 4.3.0 (64-bit)
All new SiteFab requirements has been installed.

Stack trace:
`[Pre processing]
|-Execution:  50%|#####     | 1/2 [00:01<00:01,  1.50s/ plugin]
Traceback (most recent call last):
  File "..\SiteFab\sitefab.py", line 117, in <module>
    generate(config)
  File "..\SiteFab\sitefab.py", line 53, in generate
    site.preprocessing()
  File "D:\projects\SiteFab\SiteFab\SiteFab.py", line 95, in preprocessing
    self.execute_plugins([1], "SitePreparsing", " plugin")
  File "D:\projects\SiteFab\SiteFab\SiteFab.py", line 378, in execute_plugins
    results = self.plugins.run_plugins(items, plugin_class, unit, self)
  File "D:\projects\SiteFab\SiteFab\Plugins.py", line 355, in run_plugins
    result = plugin.plugin_object.process(item, site, config)
  File "D:\projects\SiteFab\plugins\site\preparsing\responsive_images\responsive_images.py", line 177, in process
    cache_file = os.path.join(site.config.dir.cache, config.cache_name)
  File "C:\Users\XXXXX\Anaconda2\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\XXXXX\Anaconda2\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
`

**Comment by ebursztein** [comment]
cache/ conf not created and directory not created. 
Will add a linter in rc1
