### ISSUE TITLE
 'resize_images' is undefined

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#90]
I got an error during generation when i try to get resized banner

`{{  resize_images[post.meta.banner] }}`

Stacktrace
```
[Rendering]

Rendering posts
Traceback (most recent call last):
  File "..\SiteFab\sitefab.py", line 117, in <module>
    generate(config)
  File "..\SiteFab\sitefab.py", line 63, in generate
    site.render()
  File "D:\projects\SiteFab\SiteFab\SiteFab.py", line 192, in render
    self.render_posts()
  File "D:\projects\SiteFab\SiteFab\SiteFab.py", line 249, in render_posts
    rv = template.render(content=html, meta=post.meta, categories=self.posts_by_category.get_as_dict(), tags=self.posts_by_tag.get_as_dict(),            templates=self.posts_by_template.get_as_dict(), microdata=self.posts_by_microdata.get_as_dict())
  File "C:\Users\MarlburroW\Anaconda2\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\MarlburroW\Anaconda2\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\projects\elie.net\templates/index.html", line 3, in top-level template code
    {% set current_page = 'home' %}
  File "D:\projects\elie.net\templates/base.html", line 96, in top-level template code
    {% block body %} {% endblock %}
  File "D:\projects\elie.net\templates/index.html", line 197, in block "body"
    {{  resize_images[post.meta.banner] }}
  File "C:\Users\MarlburroW\Anaconda2\lib\site-packages\jinja2\environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'resize_images' is undefined
```

**Comment by ebursztein** [comment]
Investigated it: Turnout you  get the error when the post have a banner which has an incorrect URL. Banner url are expected to be local such as: /static/images/banner/fuller-house-exposing-high-end-poker-cheating-devices.jpg if it is not local then the path can't be found obviously

Fix is to make sure the post have a banner that point to a local file
Additional work around is to add a conditional test in the template:
{% if post.meta.banner in resize_images %}
{{ resize_images[post.meta.banner] }}
{% endif %}

**Comment by ebursztein** [comment]
Resized images are now available in templates as follow
```
{{plugin_data.resize_images[src]}}
```
where src is the url of the image
