### ISSUE TITLE
Collection plugin make the generation crashing

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#91]
Some posts makes the generation crashing, I don't know exactly what it is (see last *.md commits)

StackTrace
```
Traceback (most recent call last):
  File "..\SiteFab\sitefab.py", line 117, in <module> plugin/s]
    generate(config)
  File "..\SiteFab\sitefab.py", line 60, in generate
    site.process()
  File "D:\projects\SiteFab\SiteFab\SiteFab.py", line 179, in process
    self.execute_plugins(self.posts_by_template.get_as_list(), "CollectionProcessor", " templates")
  File "D:\projects\SiteFab\SiteFab\SiteFab.py", line 311, in execute_plugins
    results = self.plugins.run_plugins(items, plugin_class, unit, self)
  File "D:\projects\SiteFab\SiteFab\Plugins.py", line 372, in run_plugins
    result = plugin.plugin_object.process(item, site, config)
  File "D:\projects\SiteFab\plugins\collection\processor\compute_full_collection_url\compute_full_collection_url.py", line 8, in process
    safe = collection.meta.name.replace(" ", "-").lower()
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by ebursztein** [comment]
Fixed during this week patch cycle
